# Simple workflow for deploying static custom sample content to GitHub Pages
name: Deploy custom sample to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout custom repository
        uses: actions/checkout@v4
        with:
          path: dmesh-studio-custom-sample

      - name: Checkout base repository
        uses: actions/checkout@v4
        with:
          repository: dmesh-zone/dmesh-studio
          path: dmesh-studio

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'dmesh-studio/frontend/package-lock.json'

      - name: Install dependencies
        working-directory: ./dmesh-studio/frontend
        run: npm ci

      - name: Apply Customizations
        working-directory: ./dmesh-studio
        run: python3 scripts/base/customization.py sample

      - name: Build
        working-directory: ./dmesh-studio/frontend
        # Build with the correct base path for the custom repo
        run: npm run build -- --base=/dmesh-studio-custom-sample/

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dmesh-studio/frontend/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
